/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SomethingImport } from './routes/something'
import { Route as SidebarImport } from './routes/sidebar'
import { Route as IndexImport } from './routes/index'
import { Route as WebsiteIndexImport } from './routes/website/index'
import { Route as SidebarIndexImport } from './routes/sidebar/index'
import { Route as WebsiteSignupImport } from './routes/website/signup'
import { Route as WebsiteRegisterImport } from './routes/website/register'
import { Route as WebsiteLoginImport } from './routes/website/login'
import { Route as SidebarPaymentsImport } from './routes/sidebar/payments'
import { Route as SidebarLoanRequestImport } from './routes/sidebar/loan-request'
import { Route as SidebarEditprofileImport } from './routes/sidebar/editprofile'

// Create Virtual Routes

const FeaturesLazyImport = createFileRoute('/features')()
const ContactLazyImport = createFileRoute('/contact')()
const BlogsLazyImport = createFileRoute('/blogs')()
const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const FeaturesLazyRoute = FeaturesLazyImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/features.lazy').then((d) => d.Route))

const ContactLazyRoute = ContactLazyImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))

const BlogsLazyRoute = BlogsLazyImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/blogs.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const SomethingRoute = SomethingImport.update({
  id: '/something',
  path: '/something',
  getParentRoute: () => rootRoute,
} as any)

const SidebarRoute = SidebarImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => rootRoute,
} as any)

const WebsiteIndexRoute = WebsiteIndexImport.update({
  id: '/website/',
  path: '/website/',
  getParentRoute: () => rootRoute,
} as any)

const SidebarIndexRoute = SidebarIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRoute,
} as any)

const WebsiteSignupRoute = WebsiteSignupImport.update({
  id: '/website/signup',
  path: '/website/signup',
  getParentRoute: () => rootRoute,
} as any)

const WebsiteRegisterRoute = WebsiteRegisterImport.update({
  id: '/website/register',
  path: '/website/register',
  getParentRoute: () => rootRoute,
} as any)

const WebsiteLoginRoute = WebsiteLoginImport.update({
  id: '/website/login',
  path: '/website/login',
  getParentRoute: () => rootRoute,
} as any)

const SidebarPaymentsRoute = SidebarPaymentsImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SidebarRoute,
} as any)

const SidebarLoanRequestRoute = SidebarLoanRequestImport.update({
  id: '/loan-request',
  path: '/loan-request',
  getParentRoute: () => SidebarRoute,
} as any)

const SidebarEditprofileRoute = SidebarEditprofileImport.update({
  id: '/editprofile',
  path: '/editprofile',
  getParentRoute: () => SidebarRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sidebar': {
      id: '/sidebar'
      path: '/sidebar'
      fullPath: '/sidebar'
      preLoaderRoute: typeof SidebarImport
      parentRoute: typeof rootRoute
    }
    '/something': {
      id: '/something'
      path: '/something'
      fullPath: '/something'
      preLoaderRoute: typeof SomethingImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/sidebar/editprofile': {
      id: '/sidebar/editprofile'
      path: '/editprofile'
      fullPath: '/sidebar/editprofile'
      preLoaderRoute: typeof SidebarEditprofileImport
      parentRoute: typeof SidebarImport

    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyImport
      parentRoute: typeof rootRoute
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesLazyImport
      parentRoute: typeof rootRoute

    }
    '/sidebar/loan-request': {
      id: '/sidebar/loan-request'
      path: '/loan-request'
      fullPath: '/sidebar/loan-request'
      preLoaderRoute: typeof SidebarLoanRequestImport
      parentRoute: typeof SidebarImport
    }
    '/sidebar/payments': {
      id: '/sidebar/payments'
      path: '/payments'
      fullPath: '/sidebar/payments'
      preLoaderRoute: typeof SidebarPaymentsImport
      parentRoute: typeof SidebarImport
    }
    '/website/login': {
      id: '/website/login'
      path: '/website/login'
      fullPath: '/website/login'
      preLoaderRoute: typeof WebsiteLoginImport
      parentRoute: typeof rootRoute
    }
    '/website/register': {
      id: '/website/register'
      path: '/website/register'
      fullPath: '/website/register'
      preLoaderRoute: typeof WebsiteRegisterImport
      parentRoute: typeof rootRoute
    }
    '/website/signup': {
      id: '/website/signup'
      path: '/website/signup'
      fullPath: '/website/signup'
      preLoaderRoute: typeof WebsiteSignupImport
      parentRoute: typeof rootRoute
    }
    '/sidebar/': {
      id: '/sidebar/'
      path: '/'
      fullPath: '/sidebar/'
      preLoaderRoute: typeof SidebarIndexImport
      parentRoute: typeof SidebarImport
    }
    '/website/': {
      id: '/website/'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface SidebarRouteChildren {
  SidebarEditprofileRoute: typeof SidebarEditprofileRoute
  SidebarLoanRequestRoute: typeof SidebarLoanRequestRoute
  SidebarPaymentsRoute: typeof SidebarPaymentsRoute
  SidebarIndexRoute: typeof SidebarIndexRoute
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarEditprofileRoute: SidebarEditprofileRoute,
  SidebarLoanRequestRoute: SidebarLoanRequestRoute,
  SidebarPaymentsRoute: SidebarPaymentsRoute,
  SidebarIndexRoute: SidebarIndexRoute,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

export interface FileRoutesByFullPath {
  '/sidebar': typeof SidebarRouteWithChildren
  '/something': typeof SomethingRoute
  '/about': typeof AboutLazyRoute
  '/sidebar/editprofile': typeof SidebarEditprofileRoute
  '/blogs': typeof BlogsLazyRoute
  '/contact': typeof ContactLazyRoute
  '/features': typeof FeaturesLazyRoute
  '/sidebar/loan-request': typeof SidebarLoanRequestRoute
  '/sidebar/payments': typeof SidebarPaymentsRoute
  '/website/login': typeof WebsiteLoginRoute
  '/website/register': typeof WebsiteRegisterRoute
  '/website/signup': typeof WebsiteSignupRoute
  '/sidebar/': typeof SidebarIndexRoute
  '/website': typeof WebsiteIndexRoute
}

export interface FileRoutesByTo {
  '/something': typeof SomethingRoute
  '/about': typeof AboutLazyRoute
  '/sidebar/editprofile': typeof SidebarEditprofileRoute
  '/blogs': typeof BlogsLazyRoute
  '/contact': typeof ContactLazyRoute
  '/features': typeof FeaturesLazyRoute
  '/sidebar/loan-request': typeof SidebarLoanRequestRoute
  '/sidebar/payments': typeof SidebarPaymentsRoute
  '/website/login': typeof WebsiteLoginRoute
  '/website/register': typeof WebsiteRegisterRoute
  '/website/signup': typeof WebsiteSignupRoute
  '/sidebar': typeof SidebarIndexRoute
  '/website': typeof WebsiteIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/sidebar': typeof SidebarRouteWithChildren
  '/something': typeof SomethingRoute
  '/about': typeof AboutLazyRoute
  '/sidebar/editprofile': typeof SidebarEditprofileRoute
  '/blogs': typeof BlogsLazyRoute
  '/contact': typeof ContactLazyRoute
  '/features': typeof FeaturesLazyRoute
  '/sidebar/loan-request': typeof SidebarLoanRequestRoute
  '/sidebar/payments': typeof SidebarPaymentsRoute
  '/website/login': typeof WebsiteLoginRoute
  '/website/register': typeof WebsiteRegisterRoute
  '/website/signup': typeof WebsiteSignupRoute
  '/sidebar/': typeof SidebarIndexRoute
  '/website/': typeof WebsiteIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sidebar'
    | '/something'
    | '/about'
    | '/sidebar/editprofile'
    | '/blogs'
    | '/contact'
    | '/features'
    | '/sidebar/loan-request'
    | '/sidebar/payments'
    | '/website/login'
    | '/website/register'
    | '/website/signup'
    | '/sidebar/'
    | '/website'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/something'
    | '/about'
    | '/sidebar/editprofile'
    | '/blogs'
    | '/contact'
    | '/features'
    | '/sidebar/loan-request'
    | '/sidebar/payments'
    | '/website/login'
    | '/website/register'
    | '/website/signup'
    | '/sidebar'
    | '/website'
  id:
    | '__root__'
    | '/sidebar'
    | '/something'
    | '/about'
    | '/sidebar/editprofile'
    | '/blogs'
    | '/contact'
    | '/features'
    | '/sidebar/loan-request'
    | '/sidebar/payments'
    | '/website/login'
    | '/website/register'
    | '/website/signup'
    | '/sidebar/'
    | '/website/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SidebarRoute: typeof SidebarRouteWithChildren
  SomethingRoute: typeof SomethingRoute
  AboutLazyRoute: typeof AboutLazyRoute
  BlogsLazyRoute: typeof BlogsLazyRoute
  ContactLazyRoute: typeof ContactLazyRoute
  FeaturesLazyRoute: typeof FeaturesLazyRoute
  WebsiteLoginRoute: typeof WebsiteLoginRoute
  WebsiteRegisterRoute: typeof WebsiteRegisterRoute
  WebsiteSignupRoute: typeof WebsiteSignupRoute
  WebsiteIndexRoute: typeof WebsiteIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SidebarRoute: SidebarRouteWithChildren,
  SomethingRoute: SomethingRoute,
  AboutLazyRoute: AboutLazyRoute,
  BlogsLazyRoute: BlogsLazyRoute,
  ContactLazyRoute: ContactLazyRoute,
  FeaturesLazyRoute: FeaturesLazyRoute,
  WebsiteLoginRoute: WebsiteLoginRoute,
  WebsiteRegisterRoute: WebsiteRegisterRoute,
  WebsiteSignupRoute: WebsiteSignupRoute,
  WebsiteIndexRoute: WebsiteIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/sidebar",
        "/something",
        "/about",
        "/blogs",
        "/contact",
        "/features",
        "/website/login",
        "/website/register",
        "/website/signup",
        "/website/"
      ]
    },
    "/sidebar": {
      "filePath": "sidebar.tsx",
      "children": [
        "/sidebar/editprofile",
        "/sidebar/loan-request",
        "/sidebar/payments",
        "/sidebar/"
      ]
    },
    "/something": {
      "filePath": "something.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/sidebar/editprofile": {
      "filePath": "sidebar/editprofile.tsx",
      "parent": "/sidebar"
    "/blogs": {
      "filePath": "blogs.lazy.tsx"
    },
    "/contact": {
      "filePath": "contact.lazy.tsx"
    },
    "/features": {
      "filePath": "features.lazy.tsx"
    },
    "/sidebar/loan-request": {
      "filePath": "sidebar/loan-request.tsx",
      "parent": "/sidebar"
    },
    "/sidebar/payments": {
      "filePath": "sidebar/payments.tsx",
      "parent": "/sidebar"
    },
    "/website/login": {
      "filePath": "website/login.tsx"
    },
    "/website/register": {
      "filePath": "website/register.tsx"
    },
    "/website/signup": {
      "filePath": "website/signup.tsx"
    },
    "/sidebar/": {
      "filePath": "sidebar/index.tsx",
      "parent": "/sidebar"
    },
    "/website/": {
      "filePath": "website/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
